spring.application.name=TouristReviewBackend

server.port=8081

spring.data.mongodb.uri=mongodb://localhost:27017/tourist_review_db

# JWT Configuration
app.jwt-secret=ThisIsMyVerySecureAndLongJwtSecretUsedOnlyForSigningTokensInSpringBootAndForItsSecurity!
app.jwt-expiration-milliseconds=3600000